lib/social_network_web/router.ex
defmodule SocialNetworkWeb.Router do
  use SocialNetworkWeb, :router
  require Ueberauth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {SocialNetworkWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug SocialNetworkWeb.Plugs.SetUser
  end

  pipeline :require_auth do
    plug SocialNetworkWeb.Plugs.RequireAuth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # Order of routes matters. It checks routes sequentially down,
  # so a request to /new will fall into - live "/new", PostLive.Index, :new -
  # It would otherwise fall into - live "/:id", PostLive.Show, :show -
  # where "new" would be interpreted as an id.
  live_session :user, on_mount: {SocialNetworkWeb.LiveViewAssigns, :user} do
    scope "/", SocialNetworkWeb do
      pipe_through [:browser, :require_auth]

      live "/new", PostLive.Index, :new
      live "/:id/edit", PostLive.Index, :edit
      live "/:id/show/edit", PostLive.Show, :edit
    end

    scope "/", SocialNetworkWeb do
      pipe_through :browser

      live "/", PostLive.Index, :index
      live "/:id", PostLive.Show, :show
    end
  end

  scope "/auth", SocialNetworkWeb do
    pipe_through :browser
    get "/logout", Controllers.AuthController, :logout
    get "/:provider", Controllers.AuthController, :request
    get "/:provider/callback", Controllers.AuthController, :callback
    post "/:provider/callback", Controllers.AuthController, :callback
  end

  # Other scopes may use custom stacks.
  # scope "/api", SocialNetworkWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: SocialNetworkWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/social_network_web/live/live_helpers.ex
defmodule SocialNetworkWeb.LiveHelpers do
  import Phoenix.LiveView
  import Phoenix.LiveView.Helpers

  alias Phoenix.LiveView.JS

  @doc """
  Renders a live component inside a modal.

  The rendered modal receives a `:return_to` option to properly update
  the URL when the modal is closed.

  ## Examples

      <.modal return_to={Routes.post_index_path(@socket, :index)}>
        <.live_component
          module={SocialNetworkWeb.PostLive.FormComponent}
          id={@post.id || :new}
          title={@page_title}
          action={@live_action}
          return_to={Routes.post_index_path(@socket, :index)}
          post: @post
        />
      </.modal>
  """
  def modal(assigns) do
    assigns = assign_new(assigns, :return_to, fn -> nil end)

    ~H"""
    <div id="modal" class="phx-modal fade-in" phx-remove={hide_modal()}>
      <div
        id="modal-content"
        class="phx-modal-content fade-in-scale"
        phx-click-away={JS.dispatch("click", to: "#close")}
        phx-window-keydown={JS.dispatch("click", to: "#close")}
        phx-key="escape"
      >
        <%= if @return_to do %>
          <%= live_patch "✖",
            to: @return_to,
            id: "close",
            class: "phx-modal-close",
            phx_click: hide_modal()
          %>
        <% else %>
         <a id="close" href="#" class="phx-modal-close" phx-click={hide_modal()}>✖</a>
        <% end %>

        <%= render_slot(@inner_block) %>
      </div>
    </div>
    """
  end

  defp hide_modal(js \\ %JS{}) do
    js
    |> JS.hide(to: "#modal", transition: "fade-out")
    |> JS.hide(to: "#modal-content", transition: "fade-out-scale")
  end
end

lib/social_network_web/live/live_view_assigns.ex
defmodule SocialNetworkWeb.LiveViewAssigns do
  import Phoenix.LiveView
  alias SocialNetwork.Repo
  alias SocialNetwork.Schema.User

  def on_mount(:user, _params, session, socket) do
    user_id = Map.get(session, "user_id")

    socket =
      assign_new(socket, :current_user, fn ->
        get_user_if_not_nil(user_id)
      end)

    {:cont, socket}
  end

  # pattern matching functions
  # if function receives nil, it will match to this definition
  defp get_user_if_not_nil(nil) do
    nil
  end

  # if function does not receive nil, it will match to this definition
  defp get_user_if_not_nil(user_id) do
    Repo.get(User, user_id)
  end

  # def on_mount(:owns_target, %{"id" => id} = _params, %{"user_id" => user_id} = _session, socekt) do
  #   socket = assign_new(socket, :owns_target, fn ->
  #     post = id && Posts.get_post(id) ->
  #       post.user_id == user_id
  #   end)
  # end
end

lib/social_network_web/live/page_live.ex
defmodule SocialNetworkWeb.PageLive do
  use SocialNetworkWeb, :live_view

  @impl true
  def mount(_params, _session, socket) do
    {:ok, assign(socket, query: "", results: %{})}
  end

  @impl true
  def handle_event("suggest", %{"q" => query}, socket) do
    {:noreply, assign(socket, results: search(query), query: query)}
  end

  @impl true
  def handle_event("search", %{"q" => query}, socket) do
    case search(query) do
      %{^query => vsn} ->
        {:noreply, redirect(socket, external: "https://hexdocs.pm/#{query}/#{vsn}")}

      _ ->
        {:noreply,
         socket
         |> put_flash(:error, "No dependencies found matching \"#{query}\"")
         |> assign(results: %{}, query: query)}
    end
  end

  defp search(query) do
    if not SocialNetworkWeb.Endpoint.config(:code_reloader) do
      raise "action disabled when not in development"
    end

    for {app, desc, vsn} <- Application.started_applications(),
        app = to_string(app),
        String.starts_with?(app, query) and not List.starts_with?(desc, ~c"ERTS"),
        into: %{},
        do: {app, vsn}
  end
end

lib/social_network_web/live/post_live/form_component.ex
defmodule SocialNetworkWeb.PostLive.FormComponent do
  use SocialNetworkWeb, :live_component

  alias SocialNetwork.Repositories.Posts
  alias SocialNetwork.Schema.Post
  alias SocialNetworkWeb.Router.Helpers, as: Routes

  @impl true
  def update(%{post: post} = assigns, socket) do
    changeset = Posts.change_post(post)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)}
  end

  @impl true
  def handle_event("validate", %{"post" => post_params}, socket) do
    changeset =
      socket.assigns.post
      |> Posts.change_post(post_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"post" => post_params}, socket) do
    current_user = socket.assigns.current_user

    if current_user do
      save_post(socket, socket.assigns.action, post_params, current_user)
    else
      # put_flash doesn't work, need to figure out how to display an error here
      put_flash(socket, :error, "You must be logged in to do that.")
      {:noreply, socket}
    end
  end

  defp save_post(socket, :edit, post_params, _user) do
    case Posts.update_post(socket.assigns.post, post_params) do
      {:ok, _post} ->
        {:noreply,
         socket
         |> put_flash(:info, "Post updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_post(socket, :new, post_params, user) do
    case Posts.create_post(post_params, user) do
      {:ok, _post} ->
        {:noreply,
         socket
         |> put_flash(:info, "Post created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

lib/social_network_web/live/post_live/index.ex
defmodule SocialNetworkWeb.PostLive.Index do
  use SocialNetworkWeb, :live_view

  alias SocialNetwork.Repositories.Posts
  alias SocialNetwork.Schema.Post

  @impl true
  def mount(_params, _session, socket) do
    {:ok, assign(socket, :posts, list_posts())}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :edit, %{"id" => id}) do
    socket
    |> assign(:page_title, "Edit Post")
    |> assign(:post, Posts.get_post!(id))
  end

  defp apply_action(socket, :new, _params) do
    socket
    |> assign(:page_title, "New Post")
    |> assign(:post, %Post{})
  end

  defp apply_action(socket, :index, _params) do
    socket
    |> assign(:page_title, "Listing Posts")
    |> assign(:post, nil)
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    post = Posts.get_post!(id)
    {:ok, _} = Posts.delete_post(post)

    {:noreply, assign(socket, :posts, list_posts())}
  end

  defp list_posts do
    Posts.list_posts()
  end
end

lib/social_network_web/live/post_live/show.ex
defmodule SocialNetworkWeb.PostLive.Show do
  use SocialNetworkWeb, :live_view

  alias SocialNetwork.Repositories.Posts

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:post, Posts.get_post!(id))}
  end

  defp page_title(:show), do: "Show Post"
  defp page_title(:edit), do: "Edit Post"
end

lib/social_network_web/live/post_live/form_component.html.heex
<div>
  <h2><%= @title %></h2>

  <.form
    let={f}
    for={@changeset}
    id="post-form"
    phx-target={@myself}
    phx-change="validate"
    phx-submit="save">
  
    <%= label f, :body %>
    <%= text_input f, :body %>
    <%= error_tag f, :body %>
  
    <div>
      <%= submit "Save", phx_disable_with: "Saving..." %>
    </div>
  </.form>
</div>

lib/social_network_web/live/post_live/index.html.heex
<h1>Listing Posts</h1>

<%= if @live_action in [:new, :edit] do %>
  <.modal return_to={Routes.post_index_path(@socket, :index)}>
    <.live_component
      module={SocialNetworkWeb.PostLive.FormComponent}
      id={@post.id || :new}
      current_user={@current_user}
      title={@page_title}
      action={@live_action}
      post={@post}
      return_to={Routes.post_index_path(@socket, :index)}
    />
  </.modal>
<% end %>

<table>
  <thead>
    <tr>
      <th>Body</th>

      <th></th>
    </tr>
  </thead>
  <tbody id="posts">
    <%= for post <- @posts do %>
      <tr id={"post-#{post.id}"}>
        <td><%= post.body %></td>

        <td>
          <span><%= live_redirect "Show", to: Routes.post_show_path(@socket, :show, post) %></span>
          <%= if @current_user && post.user_id === @current_user.id do %>
            <span><%= live_patch "Edit", to: Routes.post_index_path(@socket, :edit, post) %></span>
            <span><%= link "Delete", to: "#", phx_click: "delete", phx_value_id: post.id, data: [confirm: "Are you sure?"] %></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= if @current_user do %>
  <span><%= live_patch "New Post", to: Routes.post_index_path(@socket, :new) %></span>
<% end %>

lib/social_network_web/live/post_live/show.html.heex
<h1>Show Post</h1>

<%= if @live_action in [:edit] do %>
  <.modal return_to={Routes.post_show_path(@socket, :show, @post)}>
    <.live_component
      module={SocialNetworkWeb.PostLive.FormComponent}
      id={@post.id}
      current_user={@current_user}
      title={@page_title}
      action={@live_action}
      post={@post}
      return_to={Routes.post_show_path(@socket, :show, @post)}
    />
  </.modal>
<% end %>

<ul>

  <li>
    <strong>Body:</strong>
    <%= @post.body %>
  </li>

</ul>

<%= if @current_user && @post.user_id === @current_user.id do %>
  <span><%= live_patch "Edit", to: Routes.post_show_path(@socket, :edit, @post), class: "button" %></span> |
<% end %>
<span><%= live_redirect "Back", to: Routes.post_index_path(@socket, :index) %></span>